"""Small text helpers shared across bot handlers."""
import html

# A web-login nonce is generated by the browser as 32 hex chars. Accept only that
# shape from a deep link, so a hand-crafted t.me/...?start=login_<junk> can't
# reach the confirm keyboard (callback_data is capped at 64 bytes — an oversized
# nonce would raise while building it).
_NONCE_MIN, _NONCE_MAX = 8, 64

# How many leading characters of the nonce become the match code.
_MATCH_CODE_LEN = 4


def esc(value) -> str:
    """Escape user-controlled text before it goes into a Telegram message.

    The bot sends every message with parse_mode=HTML (see bot/main.py), so a raw
    ``&`` or ``<`` in a business/service/customer name makes Telegram reject the
    whole message ("can't parse entities") and the send silently fails. Escape
    each user-controlled VALUE (never the static template) so the markup stays
    intact. Mirrors the backend's notification_service._esc.
    """
    return html.escape(str(value if value is not None else ""), quote=False)


def is_valid_login_nonce(nonce: str) -> bool:
    """Shape check for a web-login nonce arriving from a /start deep link."""
    return (
        bool(nonce)
        and _NONCE_MIN <= len(nonce) <= _NONCE_MAX
        and all(c.isalnum() or c in "-_" for c in nonce)
    )


def login_match_code(nonce: str) -> str:
    """The short code that ties a bot login confirmation to the browser that
    asked for it.

    The browser shows this code on the login screen and the bot shows it in the
    confirmation prompt; the user is told to confirm ONLY if the two match. That
    is what stops consent phishing: an attacker can start a login, get a nonce,
    and send the victim the deep link, but they cannot put the code on the
    victim's screen — so a victim who never opened the login page has nothing to
    match and should refuse.

    The code is deliberately NOT a secret (the attacker generated the nonce, so
    they know it); its job is to bind the prompt to a screen. Derived as the
    nonce's leading characters, uppercased, so the browser can compute the exact
    same value with no crypto and no extra round trip — see makeNonce/matchCode
    in frontend/src/pages/Login.jsx.
    """
    return nonce[:_MATCH_CODE_LEN].upper()
